version: 2
updates:
  # Enable version updates for Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    # Limit the number of open PRs for version updates
    open-pull-requests-limit: 5
    # Automatically merge patch and minor updates after CI passes
    auto-merge: true
    # Group dependency updates by type
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    # Custom commit message format
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Add labels to PRs
    labels:
      - "dependencies"
      - "automated"
    # Assign reviewers for major updates
    assignees:
      - "meganerd"
    reviewers:
      - "meganerd"
    # Set target branch
    target-branch: "main"
    # Allow Dependabot to rebase PRs
    rebase-strategy: "auto"
    # Ignore specific dependencies if needed
    ignore:
      # Example: ignore major version updates for breaking changes
      # - dependency-name: "clap"
      #   update-types: ["version-update:semver-major"]
      # - dependency-name: "serde"
      #   update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
      - "ci"
    assignees:
      - "meganerd"
